default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: google_login_app_development
  host: localhost
  port: 5432
  username: postgres
  password: Bhartee@123

test:
  <<: *default
  database: google_login_app_test
  host: localhost
  port: 5432
  username: postgres
  password: Bhartee@123
